# Attogram Database - https://github.com/attogram/database
# Travis CI - https://travis-ci.org/attogram/database
language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
matrix:
  fast_finish: true
before_script:
  - composer install
script:
  - if find . -name "*.php" -exec php -l {} 2>&1 \; | grep "error,"; then exit 1; fi;
  - if [ $TRAVIS_PHP_VERSION == "7.0" ]; then composer require phpunit/phpunit ~6; fi
  - if [ $TRAVIS_PHP_VERSION == "7.1" ]; then composer require phpunit/phpunit ~7; fi
  - if [ $TRAVIS_PHP_VERSION == "7.2" ]; then composer require phpunit/phpunit ~8; fi
  - if [ $TRAVIS_PHP_VERSION == "7.3" ]; then composer require phpunit/phpunit ~9; fi
  - if [ $TRAVIS_PHP_VERSION == "7.4" ]; then composer require phpunit/phpunit ~9; fi
  - vendor/bin/phpunit;
